pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your-repo/html-site.git'
            }
        }

        stage('Cleanup Old Containers') {
            steps {
                sh '''
                    docker stop html-site || true
                    docker rm html-site || true
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t html-site .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8080:80 --name html-site html-site'
            }
        }
    }

    post {
        always {
            sh 'docker ps -a'
        }
    }
}